server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hohaipan?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1234
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
  data:
    redis:
      # 地址
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  mail:
    username: 1203521235@qq.com
    password: refpzvsjybfmibii #邮箱的登录密码 非授权码
    host: smtp.qq.com
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          starttls:
            required: true
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: false
# 日志
logging:
  charset:
    file: UTF-8
    console: UTF-8
  config: classpath:log4j2.xml
  file:
    path: logs/test.log


# MyBatis-plus配置
mybatis-plus:
  #MyBatis Mapper 对应的 XML 文件位置
  mapper-locations: classpath*:/mapper/**/*.xml
  # 搜索指定包别名
  type-aliases-package: com.hhu.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type:  assign_id
      update-strategy: not_null

HohaiPan:
  CaptchaConfig:
    # 验证码类型 可选值: LineCaptcha | ShearCaptcha | CircleCaptcha
    CaptchaType: CircleCaptcha
    CaptchaWidth: 130
    CaptchaHeight: 38
    CodeCount: 5
    LineCount: 10
    CircleCount: 5
    Thickness: 3
  JwtConfig:
    # 设置jwt签名加密时使用的秘钥
    secretKey: hhu
    # 设置jwt过期时间 单位毫秒
    expireTime: 720000
    # 设置前端传递过来的令牌名称
    tokenName: Authorization
  EmailCodeConfig:
    # 设置邮箱验证码过期时间 单位秒
    expireTime: 300  #修改该项请同步在模板文件中修改过期时间
    # 设置发送的邮箱
    sendEmail: 1203521235@qq.com
    # 设置多少秒之内不能重复发送验证码 请注意千万不能超过邮箱的验证码过期时间 不然将无法正常使用邮箱功能!!!!
    coolDownTime: 60
    # 设置是否开启冷却功能
    coolDownOpen: true